import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { AgentDef } from "../../ir/types.js";
import type { SyncAdapter, SyncContext, SyncResult } from "../types.js";
import { tomlKeyValue, tomlMultilineString } from "../toml.js";

// codex/v1 — generates .codex/agents/<slug>.toml from each agent role card.

const HEADER = "# generated by harnessfile — do not edit\n";

export function renderCodexAgent(slug: string, agent: AgentDef): string {
  const lines: string[] = [HEADER.trimEnd(), ""];
  lines.push(tomlKeyValue("name", agent.name ?? slug));
  if (agent.description) {
    lines.push(tomlKeyValue("description", agent.description));
  }
  if (agent.model) {
    lines.push(tomlKeyValue("model", agent.model));
  }
  if (agent.thinkingLevel) {
    lines.push(tomlKeyValue("model_reasoning_effort", agent.thinkingLevel));
  }
  lines.push(
    `developer_instructions = ${tomlMultilineString(agent.instructions)}`,
  );
  return lines.join("\n") + "\n";
}

export class CodexAdapter implements SyncAdapter {
  provider = "codex/v1";

  async sync(ctx: SyncContext): Promise<SyncResult> {
    const result: SyncResult = { actions: [], warnings: [], notes: [] };
    const outDir = join(ctx.root, ".codex", "agents");

    for (const [slug, agent] of Object.entries(ctx.ir.agents)) {
      const path = join(outDir, `${slug}.toml`);
      const relPath = relative(ctx.root, path);
      const content = renderCodexAgent(slug, agent);

      if (existsSync(path)) {
        const existing = readFileSync(path, "utf-8");
        if (existing === content) {
          result.actions.push({ kind: "unchanged", description: relPath });
          continue;
        }
        if (!existing.startsWith(HEADER.trimEnd())) {
          result.actions.push({
            kind: "skip",
            description: `${relPath} — not generated by harnessfile (drift)`,
          });
          result.warnings.push(
            `${relPath} exists but was not generated by harnessfile — refusing to overwrite it.`,
          );
          continue;
        }
        result.actions.push({ kind: "update", description: relPath });
      } else {
        result.actions.push({ kind: "create", description: relPath });
      }

      if (ctx.apply) {
        mkdirSync(outDir, { recursive: true });
        writeFileSync(path, content, "utf-8");
      }
    }

    return result;
  }
}
