import { describe, it, expect, beforeEach } from "vitest";
import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readlinkSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { loadHarnessDirectory } from "../src/parser/directory.js";
import { runSync } from "../src/sync/engine.js";
import { planOwnedFields } from "../src/sync/ownership.js";
import { tomlKeyValue, tomlMultilineString } from "../src/sync/toml.js";
import { renderCodexAgent } from "../src/sync/adapters/codex.js";
import { renderGithubAgent } from "../src/sync/adapters/github.js";
import {
  MulticaAdapter,
  bootstrapModel,
  type MulticaRunner,
} from "../src/sync/adapters/multica.js";
import type { SyncAdapter } from "../src/sync/types.js";

const FIXTURES = resolve(import.meta.dirname, "fixtures");
const SYNC_FIXTURE = resolve(FIXTURES, "sync-plan");

function makeTmpProject(): string {
  const dir = mkdtempSync(join(tmpdir(), "harnessfile-sync-"));
  cpSync(SYNC_FIXTURE, dir, { recursive: true });
  return dir;
}

// ---- Ownership helper (D42) ----

describe("ownership — planOwnedFields", () => {
  it("keeps all fields on create, strips owned fields on update", () => {
    const { createFields, updateFields } = planOwnedFields(
      { model: "claude-sonnet-4-6", description: "d" },
      ["model", "runtime"],
    );
    expect(createFields).toEqual({
      model: "claude-sonnet-4-6",
      description: "d",
    });
    expect(updateFields).toEqual({ description: "d" });
  });

  it("keeps everything on update when nothing is owned", () => {
    const { updateFields } = planOwnedFields({ model: "m" }, undefined);
    expect(updateFields).toEqual({ model: "m" });
  });
});

// ---- TOML emitter ----

describe("toml emitter", () => {
  it("escapes quotes and backslashes in basic strings", () => {
    expect(tomlKeyValue("k", 'say "hi" \\ done')).toBe(
      'k = "say \\"hi\\" \\\\ done"',
    );
  });

  it("uses multiline strings for bodies with newlines", () => {
    const out = tomlKeyValue("k", "line one\nline two");
    expect(out).toContain('"""');
    expect(out).toContain("line one\nline two");
  });

  it("escapes triple quotes inside multiline strings", () => {
    const out = tomlMultilineString('has """ inside');
    expect(out).not.toContain('has """ inside');
    expect(out).toContain('\\"\\"\\"');
  });
});

// ---- Codex adapter ----

describe("sync — codex/v1", () => {
  it("renders golden TOML for an agent", () => {
    const { ir } = loadHarnessDirectory(SYNC_FIXTURE);
    const toml = renderCodexAgent("triager", ir.agents["triager"]);
    expect(toml).toBe(
      `# generated by harnessfile — do not edit

name = "triager"
description = "Triages issues into actionable bug reports."
model = "claude-sonnet-4-6"
model_reasoning_effort = "high"
developer_instructions = """
# Role
You triage issues. Deduplicate, ignore noise, file genuine "bugs" only.
"""
`,
    );
  });

  it("omits model when the agent has no portable default", () => {
    const { ir } = loadHarnessDirectory(SYNC_FIXTURE);
    const toml = renderCodexAgent("engineer", ir.agents["engineer"]);
    expect(toml).not.toContain("model =");
    expect(toml).toContain("\\\\"); // escaped backslash from the body
  });

  it("plans creates on dry run without writing files", async () => {
    const dir = makeTmpProject();
    try {
      const harness = loadHarnessDirectory(dir);
      const result = await runSync(harness, {
        targetName: "codex",
        apply: false,
      });
      const creates = result.actions.filter((a) => a.kind === "create");
      expect(creates.map((a) => a.description).sort()).toEqual([
        ".codex/agents/engineer.toml",
        ".codex/agents/pm.toml",
        ".codex/agents/triager.toml",
      ]);
      expect(existsSync(join(dir, ".codex"))).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("writes files on apply and is idempotent", async () => {
    const dir = makeTmpProject();
    try {
      const harness = loadHarnessDirectory(dir);
      await runSync(harness, { targetName: "codex", apply: true });

      const tomlPath = join(dir, ".codex", "agents", "triager.toml");
      expect(existsSync(tomlPath)).toBe(true);
      expect(readFileSync(tomlPath, "utf-8")).toContain(
        "# generated by harnessfile — do not edit",
      );

      // Second run: everything unchanged
      const second = await runSync(harness, {
        targetName: "codex",
        apply: true,
      });
      expect(second.actions.every((a) => a.kind === "unchanged")).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("refuses to overwrite a hand-written file", async () => {
    const dir = makeTmpProject();
    try {
      mkdirSync(join(dir, ".codex", "agents"), { recursive: true });
      writeFileSync(
        join(dir, ".codex", "agents", "triager.toml"),
        "# my own file\n",
      );
      const harness = loadHarnessDirectory(dir);
      const result = await runSync(harness, {
        targetName: "codex",
        apply: true,
      });
      expect(result.warnings.some((w) => w.includes("triager.toml"))).toBe(
        true,
      );
      expect(readFileSync(join(dir, ".codex", "agents", "triager.toml"), "utf-8")).toBe(
        "# my own file\n",
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

// ---- GitHub Agent HQ adapter ----

describe("sync — github-agent-hq/v1", () => {
  it("renders golden markdown for an agent", () => {
    const { ir } = loadHarnessDirectory(SYNC_FIXTURE);
    const md = renderGithubAgent("pm", ir.agents["pm"]);
    expect(md).toBe(
      `---
name: pm
description: Leads the development squad.
---

You are the PM. You orchestrate the squad.
`,
    );
  });

  it("writes .github/agents/<slug>.md on apply", async () => {
    const dir = makeTmpProject();
    try {
      const harness = loadHarnessDirectory(dir);
      const result = await runSync(harness, {
        targetName: "github",
        apply: true,
      });
      expect(result.actions.filter((a) => a.kind === "create")).toHaveLength(3);
      expect(existsSync(join(dir, ".github", "agents", "engineer.md"))).toBe(
        true,
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

// ---- Claude Code adapter ----

describe("sync — claude-code/v1", () => {
  it("creates relative symlinks on apply", async () => {
    const dir = makeTmpProject();
    try {
      const harness = loadHarnessDirectory(dir);
      const result = await runSync(harness, {
        targetName: "claude-code",
        apply: true,
      });
      expect(result.actions.filter((a) => a.kind === "create")).toHaveLength(2);

      const agentsLink = join(dir, ".claude", "agents");
      const skillsLink = join(dir, ".claude", "skills");
      expect(lstatSync(agentsLink).isSymbolicLink()).toBe(true);
      expect(readlinkSync(agentsLink)).toBe("../.agents/agents");
      expect(readlinkSync(skillsLink)).toBe("../.agents/skills");
      // Symlinks resolve to real content
      expect(existsSync(join(agentsLink, "triager.md"))).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("is idempotent", async () => {
    const dir = makeTmpProject();
    try {
      const harness = loadHarnessDirectory(dir);
      await runSync(harness, { targetName: "claude-code", apply: true });
      const second = await runSync(harness, {
        targetName: "claude-code",
        apply: true,
      });
      expect(second.actions.every((a) => a.kind === "unchanged")).toBe(true);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("reports drift and never deletes an existing real directory", async () => {
    const dir = makeTmpProject();
    try {
      mkdirSync(join(dir, ".claude", "agents"), { recursive: true });
      writeFileSync(join(dir, ".claude", "agents", "mine.md"), "user data");

      const harness = loadHarnessDirectory(dir);
      const result = await runSync(harness, {
        targetName: "claude-code",
        apply: true,
      });

      const skip = result.actions.find(
        (a) => a.kind === "skip" && a.description.includes(".claude/agents"),
      );
      expect(skip).toBeDefined();
      expect(result.warnings.some((w) => w.includes(".claude/agents"))).toBe(
        true,
      );
      // User data untouched
      expect(readFileSync(join(dir, ".claude", "agents", "mine.md"), "utf-8")).toBe(
        "user data",
      );
      // The other link is still created
      expect(lstatSync(join(dir, ".claude", "skills")).isSymbolicLink()).toBe(
        true,
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

// ---- Multica adapter (fake runner) ----

interface RemoteState {
  skills: Array<{ id: string; name: string; files: Array<{ id: string; path: string }> }>;
  agents: Array<{ id: string; name: string; model?: string }>;
  squads: Array<{ id: string; name: string; members: Array<{ member_id: string; member_type: string; role: string }> }>;
  autopilots: Array<{ id: string; title: string; triggers: Array<{ id: string; kind: string; cron_expression: string; timezone: string; enabled: boolean }> }>;
  runtimes: Array<{ id: string; name: string; status: string; provider: string }>;
}

class FakeMulticaRunner implements MulticaRunner {
  calls: string[][] = [];
  envs: Array<Record<string, string> | undefined> = [];
  private ids = 0;

  constructor(
    public state: RemoteState,
    private isAvailable = true,
  ) {}

  async available(): Promise<boolean> {
    return this.isAvailable;
  }

  private nextId(prefix: string): string {
    return `${prefix}-${++this.ids}`;
  }

  async run(
    args: string[],
    extraEnv?: Record<string, string>,
  ): Promise<string> {
    this.calls.push(args);
    this.envs.push(extraEnv);
    const [domain, verb] = args;
    const key = `${domain} ${verb}`;

    switch (key) {
      case "skill list":
        return JSON.stringify(this.state.skills);
      case "agent list":
        return JSON.stringify(this.state.agents);
      case "squad list":
        return JSON.stringify(this.state.squads);
      case "runtime list":
        return JSON.stringify(this.state.runtimes);
      case "autopilot list":
        return JSON.stringify({ autopilots: this.state.autopilots });
      case "autopilot get": {
        const ap = this.state.autopilots.find((a) => a.id === args[2]);
        return JSON.stringify(ap ?? {});
      }
      case "skill create": {
        const skill = {
          id: this.nextId("skill"),
          name: flag(args, "--name")!,
          files: [],
        };
        this.state.skills.push(skill);
        return JSON.stringify(skill);
      }
      case "skill update":
      case "skill delete":
        return "{}";
      case "skill files": {
        const sub = args[2];
        if (sub === "list") {
          const skill = this.state.skills.find((s) => s.id === args[3]);
          return JSON.stringify(skill?.files ?? []);
        }
        if (sub === "upsert") {
          const skill = this.state.skills.find((s) => s.id === args[3]);
          const path = flag(args, "--path")!;
          if (skill && !skill.files.some((f) => f.path === path)) {
            skill.files.push({ id: this.nextId("file"), path });
          }
        }
        return "{}";
      }
      case "agent create": {
        const agent = {
          id: this.nextId("agent"),
          name: flag(args, "--name")!,
          model: flag(args, "--model"),
        };
        this.state.agents.push(agent);
        return JSON.stringify(agent);
      }
      case "agent update":
      case "agent skills":
        return "{}";
      case "squad create": {
        const squad = {
          id: this.nextId("squad"),
          name: flag(args, "--name")!,
          members: [],
        };
        this.state.squads.push(squad);
        return JSON.stringify(squad);
      }
      case "squad update":
        return "{}";
      case "squad member": {
        const sub = args[2];
        const squad = this.state.squads.find((s) => s.id === args[3]);
        if (sub === "list") return JSON.stringify(squad?.members ?? []);
        if (sub === "add" && squad) {
          squad.members.push({
            member_id: flag(args, "--member-id")!,
            member_type: "agent",
            role: flag(args, "--role") ?? "member",
          });
        }
        return "{}";
      }
      case "autopilot create": {
        const ap = {
          id: this.nextId("ap"),
          title: flag(args, "--title")!,
          triggers: [],
        };
        this.state.autopilots.push(ap);
        return JSON.stringify(ap);
      }
      case "autopilot update":
        return "{}";
      case "autopilot trigger-add": {
        const ap = this.state.autopilots.find((a) => a.id === args[2]);
        if (ap) {
          ap.triggers.push({
            id: this.nextId("trigger"),
            kind: "schedule",
            cron_expression: flag(args, "--cron")!,
            timezone: flag(args, "--timezone")!,
            enabled: true,
          });
        }
        return "{}";
      }
      default:
        return "{}";
    }
  }
}

function flag(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  return i === -1 ? undefined : args[i + 1];
}

function emptyRemote(): RemoteState {
  return {
    skills: [],
    agents: [],
    squads: [],
    autopilots: [],
    runtimes: [
      { id: "rt-1", name: "workstation", status: "online", provider: "claude" },
      { id: "rt-2", name: "codex-worker", status: "online", provider: "codex" },
    ],
  };
}

const WS_ENV = { MULTICA_WORKSPACE_ID: "ws-test" };

function multicaSync(
  dir: string,
  runner: MulticaRunner,
  apply: boolean,
  env: Record<string, string | undefined> = {},
  prune = false,
) {
  const harness = loadHarnessDirectory(dir);
  const adapter: SyncAdapter = new MulticaAdapter(runner, env);
  return runSync(harness, {
    targetName: "multica",
    apply,
    prune,
    adapters: [adapter],
  });
}

describe("sync — multica/v1 (fake runner)", () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTmpProject();
    return () => rmSync(dir, { recursive: true, force: true });
  });

  it("bootstrapModel prefers portable default, then env, then runtime default", () => {
    expect(bootstrapModel("claude-sonnet-5", {})).toBe("claude-sonnet-5");
    expect(bootstrapModel("custom/model-name", {})).toBe("custom/model-name");
    expect(bootstrapModel(undefined, { MULTICA_DEFAULT_MODEL: "my-model" })).toBe(
      "my-model",
    );
    expect(bootstrapModel(undefined, {})).toBeUndefined();
  });

  it("dry-run plans creates against an empty remote in order: skills, agents, squads, autopilots", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    const result = await multicaSync(dir, runner, false);

    const descriptions = result.actions.map((a) => a.description);
    const skillIdx = descriptions.findIndex((d) => d.includes("create skill greeting"));
    const agentIdx = descriptions.findIndex((d) => d.includes("create agent Triager"));
    const squadIdx = descriptions.findIndex((d) => d.includes("create squad Development"));
    const apIdx = descriptions.findIndex((d) => d.includes("create autopilot nightly-sweep"));
    expect(skillIdx).toBeGreaterThanOrEqual(0);
    expect(agentIdx).toBeGreaterThan(skillIdx);
    expect(squadIdx).toBeGreaterThan(agentIdx);
    expect(apIdx).toBeGreaterThan(squadIdx);

    // No mutating calls in dry-run — only read-only list commands
    for (const call of runner.calls) {
      expect(call.join(" ")).toMatch(/list|get/);
    }
  });

  it("dry-run works without the multica CLI and notes the unknown remote state", async () => {
    const runner = new FakeMulticaRunner(emptyRemote(), false);
    const result = await multicaSync(dir, runner, false);
    expect(
      result.notes.some((n) => n.includes("multica CLI not found")),
    ).toBe(true);
    expect(
      result.actions.some((a) => a.description.includes("create agent Triager")),
    ).toBe(true);
    expect(runner.calls).toHaveLength(0);
  });

  it("--apply errors cleanly when the multica CLI is missing", async () => {
    const runner = new FakeMulticaRunner(emptyRemote(), false);
    await expect(multicaSync(dir, runner, true)).rejects.toThrow(
      "multica CLI not found — cannot apply",
    );
  });

  it("--apply errors without an explicit workspace binding", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    await expect(multicaSync(dir, runner, true)).rejects.toThrow(
      "multica target requires an explicit workspace: set MULTICA_WORKSPACE_ID or targets.multica.x-workspace — refusing to mutate the ambient login's workspace",
    );
    // Nothing mutated
    expect(runner.state.agents).toHaveLength(0);
    expect(runner.state.skills).toHaveLength(0);
  });

  it("--apply passes with MULTICA_WORKSPACE_ID and exports it to every CLI call", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    await multicaSync(dir, runner, true, WS_ENV);

    expect(runner.state.agents.length).toBeGreaterThan(0);
    expect(runner.envs.length).toBeGreaterThan(0);
    for (const env of runner.envs) {
      expect(env).toEqual({ MULTICA_WORKSPACE_ID: "ws-test" });
    }
  });

  it("--apply passes with targets.multica.x-workspace in harness.yaml", async () => {
    // Bind the workspace in the harness file instead of the environment
    const harnessPath = join(dir, ".agents", "harness.yaml");
    const yaml = readFileSync(harnessPath, "utf-8").replace(
      "provider: multica/v1",
      'provider: multica/v1\n    x-workspace: "ws-from-file"',
    );
    writeFileSync(harnessPath, yaml);

    const runner = new FakeMulticaRunner(emptyRemote());
    await multicaSync(dir, runner, true);

    expect(runner.state.agents.length).toBeGreaterThan(0);
    for (const env of runner.envs) {
      expect(env).toEqual({ MULTICA_WORKSPACE_ID: "ws-from-file" });
    }
  });

  it("dry-run without a workspace binding notes the ambient workspace risk", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    const result = await multicaSync(dir, runner, false);
    expect(
      result.notes.some(
        (n) =>
          n.includes("no explicit workspace binding") &&
          n.includes("ambient"),
      ),
    ).toBe(true);
  });

  it("bootstrap seeds owned fields; a second push never touches them (D42)", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    const env = { MULTICA_DEFAULT_MODEL: "env-fallback-model", ...WS_ENV };

    // First push: agents are created with bootstrap models
    await multicaSync(dir, runner, true, env);

    const triagerCreate = runner.calls.find(
      (c) => c[0] === "agent" && c[1] === "create" && c.includes("Triager"),
    );
    expect(triagerCreate).toBeDefined();
    // Portable model is opaque and passed through unchanged.
    expect(flag(triagerCreate!, "--model")).toBe("claude-sonnet-4-6");
    expect(flag(triagerCreate!, "--thinking-level")).toBe("high");

    // engineer has no portable model → env fallback
    const engineerCreate = runner.calls.find(
      (c) => c[0] === "agent" && c[1] === "create" && c.includes("engineer"),
    );
    expect(engineerCreate).toBeDefined();
    expect(flag(engineerCreate!, "--model")).toBe("env-fallback-model");
    expect(flag(triagerCreate!, "--runtime-id")).toBe("rt-1");
    expect(flag(engineerCreate!, "--runtime-id")).toBe("rt-2");

    // Simulate the operator re-pointing the model on Multica
    runner.state.agents.find((a) => a.name === "Triager")!.model =
      "operator-tuned-model";

    // Second push: updates only, and never with --model
    runner.calls = [];
    await multicaSync(dir, runner, true, env);

    const creates = runner.calls.filter(
      (c) => c[0] === "agent" && c[1] === "create",
    );
    expect(creates).toHaveLength(0);

    const updates = runner.calls.filter(
      (c) => c[0] === "agent" && c[1] === "update",
    );
    expect(updates.length).toBeGreaterThan(0);
    for (const update of updates) {
      expect(update).not.toContain("--model");
      expect(update).not.toContain("--thinking-level");
      expect(update).toContain("--instructions");
    }
    expect(
      runner.state.agents.find((a) => a.name === "Triager")!.model,
    ).toBe("operator-tuned-model");
  });

  it("honors a target-side binding to a concrete compatible runtime instance", async () => {
    const remote = emptyRemote();
    remote.runtimes.push({
      id: "rt-codex-pinned",
      name: "pinned-codex-worker",
      status: "online",
      provider: "codex",
    });
    const runner = new FakeMulticaRunner(remote);

    await multicaSync(dir, runner, true, {
      ...WS_ENV,
      MULTICA_RUNTIME_CODEX_ID: "rt-codex-pinned",
    });

    const engineerCreate = runner.calls.find(
      (call) => call[0] === "agent" && call[1] === "create" && call.includes("engineer"),
    );
    expect(flag(engineerCreate!, "--runtime-id")).toBe("rt-codex-pinned");
  });

  it("applies the full push: skills, files, agents, squad members, autopilot trigger", async () => {
    const runner = new FakeMulticaRunner(emptyRemote());
    await multicaSync(dir, runner, true, WS_ENV);

    // Skill + supporting file
    expect(runner.state.skills.map((s) => s.name)).toEqual(["greeting"]);
    expect(runner.state.skills[0].files.map((f) => f.path)).toEqual([
      "references/styles.md",
    ]);

    // Agents (3) — display names honor multica.display_name passthrough
    expect(runner.state.agents.map((a) => a.name).sort()).toEqual([
      "Triager",
      "engineer",
      "pm",
    ]);

    // Squad with agent members
    expect(runner.state.squads.map((s) => s.name)).toEqual(["Development"]);
    expect(runner.state.squads[0].members).toHaveLength(2);

    // Autopilot from the scheduled trigger, with its cron trigger
    expect(runner.state.autopilots.map((a) => a.title)).toEqual([
      "nightly-sweep",
    ]);
    expect(runner.state.autopilots[0].triggers[0].cron_expression).toBe(
      "0 3 * * *",
    );
    expect(runner.state.autopilots[0].triggers[0].timezone).toBe("UTC");

    // The autopilot description is the resolved prompt text
    const apCreate = runner.calls.find(
      (c) => c[0] === "autopilot" && c[1] === "create",
    );
    expect(flag(apCreate!, "--description")).toBe(
      "Run the nightly sweep and file genuine bugs only.",
    );
  });

  it("deletes remote skills absent from the union of agent skills (with --prune)", async () => {
    const remote = emptyRemote();
    remote.skills.push({ id: "skill-stale", name: "obsolete", files: [] });
    const runner = new FakeMulticaRunner(remote);

    await multicaSync(dir, runner, true, WS_ENV, true);

    const deleteCall = runner.calls.find(
      (c) => c[0] === "skill" && c[1] === "delete" && c[2] === "skill-stale",
    );
    expect(deleteCall).toBeDefined();
  });

  it("without --prune, plans skipped deletions instead of deletes", async () => {
    const remote = emptyRemote();
    remote.skills.push({ id: "skill-stale", name: "obsolete", files: [] });
    const runner = new FakeMulticaRunner(remote);

    // Dry run without prune
    const dryRun = await multicaSync(dir, runner, false);
    expect(
      dryRun.actions.some(
        (a) =>
          a.kind === "skip" &&
          a.description ===
            "would delete remote skill obsolete (pass --prune to include)",
      ),
    ).toBe(true);
    expect(
      dryRun.actions.some((a) => a.description.includes("delete remote skill obsolete (not assigned")),
    ).toBe(false);
    expect(dryRun.skippedDeletions).toBe(1);

    // Apply without prune: still no deletion issued
    runner.calls = [];
    const applied = await multicaSync(dir, runner, true, WS_ENV);
    expect(applied.skippedDeletions).toBe(1);
    const deleteCalls = runner.calls.filter(
      (c) => c[0] === "skill" && c[1] === "delete",
    );
    expect(deleteCalls).toHaveLength(0);
    expect(runner.state.skills.some((s) => s.name === "obsolete")).toBe(true);
  });

  it("without --prune, stale skill files are skipped, not deleted", async () => {
    const remote = emptyRemote();
    remote.skills.push({
      id: "skill-greeting",
      name: "greeting",
      files: [{ id: "file-stale", path: "references/removed.md" }],
    });
    const runner = new FakeMulticaRunner(remote);

    const result = await multicaSync(dir, runner, true, WS_ENV);
    expect(
      result.actions.some(
        (a) =>
          a.kind === "skip" &&
          a.description.includes(
            "would delete stale skill file greeting/references/removed.md",
          ),
      ),
    ).toBe(true);
    const fileDeletes = runner.calls.filter(
      (c) => c[0] === "skill" && c[1] === "files" && c[2] === "delete",
    );
    expect(fileDeletes).toHaveLength(0);

    // With prune, the stale file goes
    runner.calls = [];
    await multicaSync(dir, runner, true, WS_ENV, true);
    expect(
      runner.calls.some(
        (c) =>
          c[0] === "skill" &&
          c[1] === "files" &&
          c[2] === "delete" &&
          c.includes("file-stale"),
      ),
    ).toBe(true);
  });

  it("skips agent bootstrap when no runtime is online", async () => {
    const remote = emptyRemote();
    remote.runtimes = [];
    const runner = new FakeMulticaRunner(remote);

    const result = await multicaSync(dir, runner, true, WS_ENV);
    expect(
      result.warnings.some((w) => w.includes("no ONLINE runtime")),
    ).toBe(true);
    expect(runner.state.agents).toHaveLength(0);
  });

  it("never places a profiled agent on a different runtime family", async () => {
    const remote = emptyRemote();
    remote.runtimes = remote.runtimes.filter((runtime) => runtime.provider === "claude");
    const runner = new FakeMulticaRunner(remote);

    const result = await multicaSync(dir, runner, true, WS_ENV);
    expect(runner.state.agents.some((agent) => agent.name === "engineer")).toBe(false);
    expect(runner.state.agents.some((agent) => agent.name === "Triager")).toBe(true);
    expect(
      result.warnings.some(
        (warning) => warning.includes("agent 'engineer'") && warning.includes("no ONLINE runtime"),
      ),
    ).toBe(true);
  });
});

// ---- Engine ----

describe("sync engine", () => {
  it("rejects an unknown target", async () => {
    const harness = loadHarnessDirectory(SYNC_FIXTURE);
    await expect(
      runSync(harness, { targetName: "nope", apply: false }),
    ).rejects.toThrow("Target 'nope' is not defined");
  });
});
